
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
   prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      endpoints:
        default: https://weby-ee924decca.herokuapp.com/graphqwith prisma/dev

      output:
          binding: src/generated/prisma.js
